version: '3.8'

services:
  app:
    container_name: batch_server
    build:
      context: ./youtubeBatch
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - STAGE=local
      - REGION=ap-northeast-2
    volumes:
      - ./csv_data:/data  # 호스트 csv_data를 컨테이너 /data에 마운트
    working_dir: /home/app
    command: ['java', '-jar', '/app/app.jar']
    networks:
      - infra-net

  dash:
    container_name: dash
    build:
      context: ./dash
      dockerfile: Dockerfile
    ports:
      - '8050:8050'
    volumes:
      - ./csv_data:/data  # 동일한 경로 마운트
    working_dir: /app
    command: ['python', 'app.py']
    networks:
      - infra-net

networks:
  infra-net:
    driver: bridge
