version: '3.8'

services:
  app:
    container_name: batch_server
    build:
      context: ./youtubeBatch
      dockerfile: Dockerfile
      args:
        - GRADLE_OPTS=-Dorg.gradle.daemon=false
    ports:
      - '0.0.0.0:8080:8080'
    environment:
      - STAGE=local
      - REGION=ap-northeast-2
      - CSV_DATA_PATH=/data
      - DASH_IP=dash
      - DASH_PORT=8050
      - BATCH_JOB_FIXED_RATE=14400000
    volumes:
      - ${PWD}/csv_data:/data:rw
      - ./youtubeBatch/src:/app/src:rw
    working_dir: /app
    command: ['sh', '-c', 'sleep 60 && java -jar /app/app.jar']
    # command: ['java', '-jar', '/app/app.jar']
    networks:
      - infra-net

  dash:
    container_name: dash
    build:
      context: ./UI
      dockerfile: Dockerfile
    ports:
      - '0.0.0.0:8050:8050'
    environment:
      - CSV_DATA_PATH=/youtube_data
      - PYTHONUNBUFFERED=1
      - DASH_HOST=0.0.0.0
    volumes:
      # - ${PWD}/csv_data:/youtube_data:rw
      - ${PWD}/csv_data:/app/youtube_data:rw
      - ./UI/Font:/app/Font
    working_dir: /app
    command: python main.py
    networks:
      - infra-net
#    depends_on:
#      - app

networks:
  infra-net:
    driver: bridge
